// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFn7L4b7cJWFkpkqmKEzF1XFxBJZBj664',
    appId: '1:683502200957:web:957fff3b104b11de2e6914',
    messagingSenderId: '683502200957',
    projectId: 'evently-app-1395e',
    authDomain: 'evently-app-1395e.firebaseapp.com',
    storageBucket: 'evently-app-1395e.firebasestorage.app',
    measurementId: 'G-29JDM8ME1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo6SloOZHHielZA-aMlL8jzX7jiwxKqNA',
    appId: '1:683502200957:android:90fbcc4331bf06152e6914',
    messagingSenderId: '683502200957',
    projectId: 'evently-app-1395e',
    storageBucket: 'evently-app-1395e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvLACN6elgKvh1o6SBD7kSB1DuiK6GZ_I',
    appId: '1:683502200957:ios:fb3063d9f8e19aa12e6914',
    messagingSenderId: '683502200957',
    projectId: 'evently-app-1395e',
    storageBucket: 'evently-app-1395e.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvLACN6elgKvh1o6SBD7kSB1DuiK6GZ_I',
    appId: '1:683502200957:ios:fb3063d9f8e19aa12e6914',
    messagingSenderId: '683502200957',
    projectId: 'evently-app-1395e',
    storageBucket: 'evently-app-1395e.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFn7L4b7cJWFkpkqmKEzF1XFxBJZBj664',
    appId: '1:683502200957:web:706fa43dde7768762e6914',
    messagingSenderId: '683502200957',
    projectId: 'evently-app-1395e',
    authDomain: 'evently-app-1395e.firebaseapp.com',
    storageBucket: 'evently-app-1395e.firebasestorage.app',
    measurementId: 'G-JENFR3YJXL',
  );
}
